import { Scenario } from "../../../electron/src/types/scenario";

export const INITIAL_SCENARIO: Scenario = {
  projectId: "",
  debugMode: "debug",
  durationBased: true,
  scriptConfigs: [],
  iterations: 1,
  thinkTime: 100,
  projectName: "",
  name: "Scenario Initial Name",
  createDateString: "",
  scenarioId: "",
  useScriptSettings: true,
  duration: 7,
  thinkTimeMode: "recorded",
  pauseForIPs: false,
  accountId: "",
  rampUpSteps: 10,
  vusPerScript: [],
  runWithTunnel: false,
  vusPerRegion: [5, 5],
  timeoutDelay: 30,
  totalUsers: 10,
  iterationDelay: 30,
  enableDebugTime: 1,
  geoDistr: [],
  createDate: "",
  fullLoadDuration: 5,
  rampUp: 2,
  machineType: "standard",
  recommendedMachineType: false,
};

export const BLANK_SCENARIO = {
  scenarioName: "Sample scenario new",
  dedicatedProduct: "TC",
  durationBased: true,
  durationM: 5,
  iterations: 5,
  iterationDelayS: 3,
  rampUpM: 1,
  thinkTimeMode: "fixed",
  thinkTimeMS: 155,
  timeoutDelayS: 200,
  scripts: [],
};
